apiVersion: v1
kind: Service
metadata:
  name: exemplo-service
  namespace: exemplo-ns
  labels:
    app: exemplo
    monitoring: metrics-text
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
  selector:
    app: exemplo
