apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: exemplo-hpa
  namespace: exemplo-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: exemplo-deployment
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: application_httprequests_active
      target:
        type: AverageValue
        averageValue: "10"
  # - type: Resource
  #   resource:
  #     name: cpu
  #     target:
  #       type: Utilization
  #       averageUtilization: 50
