apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  selector:
    matchLabels:
      app: example
  replicas: 4 # quantidade de pods que devem ser criados
  template:
    metadata:
      labels:
        app: example
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: example-app
        image: xavero/weather:4.0.0
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        resources:
            requests: 
              memory: 20Mi
              cpu: 10m # 1% de uma cpu
            limits: 
              memory: 100Mi
              cpu: 500m # 50% de uma cpu
        env:
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
          
---

apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: example
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
    nodePort: 32000
  selector:
    app: example
