## Install with helm: 
##    helm repo add bitnami https://charts.bitnami.com/bitnami
##    helm repo update
##    helm install metrics-server bitnami/metrics-server -f metrics-server-values.yaml --namespace monitoring --create-namespace --atomic

image:
  registry: docker.io
  repository: bitnami/metrics-server
  tag: 0.5.0-debian-10-r32

## API service parameters
##
apiService:
  ## @param apiService.create Specifies whether the v1beta1.metrics.k8s.io API service should be created. You can check if it is needed with `kubectl get --raw "/apis/metrics.k8s.io/v1beta1/nodes"`.
  ## This is still necessary up to at least k8s version >= 1.21, but depends on vendors and cloud providers.
  ##
  create: true

extraArgs:
  # DONT USE INSECURE IN PRODUCTION!
  kubelet-insecure-tls: true 
  kubelet-preferred-address-types: InternalIP
